name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWSRestartDeployer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH for EC2 login
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
              chmod 600 ~/.ssh/deploy-key
              GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy-key -o StrictHostKeyChecking=no" \
                git clone git@github.com:nekkuzuria/terraform-project.git

              sudo cp terraform-project/hello.html /var/www/html/index.html
              sudo systemctl restart httpd

              sudo rm -rf terraform-project
          EOF
